### ISSUE TITLE
Add new FDSNWS links for the one that was not listed on FDSN site

### ISSUE THREAD

**Issue by weetme063** [YacineBoussoufa/EarthquakeDataCenters#2]
BMKG:
https://geof.bmkg.go.id/fdsnws/station/1/

SNAC NOA:
http://snac.gein.noa.gr:8080/fdsnws/station/1/

INETER (as of this writing, it had problem on its server):
http://catac.ineter.gob.ni/fdsnws/station/1/

GEONET (archive link):
https://service.geonet.org.nz/fdsnws/station/1/

**Comment by weetme063** [comment]
KNMI (Non-ORFEUS site):
http://rdsa.knmi.nl/fdsnws/station/1/

**Comment by YacineBoussoufa** [comment]
INETER and GEONET are not working. Considered as Invalid.
